### ISSUE TITLE
Cannot clone job to computer

### ISSUE THREAD

**Issue by Amanpradhan** [floydhub/floyd-cli#102]
Downloading the tar file to the current directory ...
Traceback (most recent call last):
  File "/home/aman/anaconda3/bin/floyd", line 11, in <module>
    sys.exit(cli())
  File "/home/aman/anaconda3/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/aman/anaconda3/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/aman/anaconda3/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/aman/anaconda3/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/aman/anaconda3/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/aman/anaconda3/lib/python3.5/site-packages/floyd/cli/experiment.py", line 93, in clone
    delete_after_untar=True)
  File "/home/aman/anaconda3/lib/python3.5/site-packages/floyd/client/base.py", line 109, in download_tar
    filename = self.download(url=url, filename='output.tar')
  File "/home/aman/anaconda3/lib/python3.5/site-packages/floyd/client/base.py", line 93, in download
    total_length = int(response.headers.get('content-length'))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

Each time this error comes and I cannot clone my project to my directory

**Comment by houqp** [comment]
Hi, sorry for the trouble, this is a known issue. We are working on a fix right now. At the mean time, you can download the code from our web UI manually to work around the issue.

**Comment by houqp** [comment]
@Amanpradhan please give the latest client a try, this bug should have been fixed in that release.
