### ISSUE TITLE
ImportError: No module named processors

### ISSUE THREAD

**Issue by adaxidedakaonang** [floydhub/floyd-cli#157]
When I followed this guide "Quick Start - Jupyter Notebook",I met some question. something happened after I finish this code`floyd run --mode jupyter`,it is:

adaxi:~ Arduino$ floyd run --gpu --mode jupyter
Error in sys.excepthook:
Traceback (most recent call last):
  File "/Users/Arduino/anaconda2/lib/python2.7/site-packages/raven/base.py", line 274, in handle_exception
  File "/Users/Arduino/anaconda2/lib/python2.7/site-packages/raven/base.py", line 814, in captureException
  File "/Users/Arduino/anaconda2/lib/python2.7/site-packages/raven/base.py", line 634, in capture
  File "/Users/Arduino/anaconda2/lib/python2.7/site-packages/raven/base.py", line 470, in build_msg
  File "/Users/Arduino/anaconda2/lib/python2.7/site-packages/raven/base.py", line 293, in get_processors
  File "/Users/Arduino/anaconda2/lib/python2.7/site-packages/raven/base.py", line 78, in __missing__
ImportError: No module named processors

Original exception was:
Traceback (most recent call last):
  File "/Users/Arduino/anaconda2/bin/floyd", line 11, in <module>
  File "/Users/Arduino/anaconda2/lib/python2.7/site-packages/click/core.py", line 722, in __call__
  File "/Users/Arduino/anaconda2/lib/python2.7/site-packages/click/core.py", line 697, in main
  File "/Users/Arduino/anaconda2/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
  File "/Users/Arduino/anaconda2/lib/python2.7/site-packages/click/core.py", line 895, in invoke
  File "/Users/Arduino/anaconda2/lib/python2.7/site-packages/click/core.py", line 535, in invoke
  File "/Users/Arduino/anaconda2/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
  File "/Users/Arduino/anaconda2/lib/python2.7/site-packages/floyd/cli/run.py", line 221, in run
  File "/Users/Arduino/anaconda2/lib/python2.7/site-packages/floyd/client/module.py", line 37, in create
  File "/Users/Arduino/anaconda2/lib/python2.7/site-packages/floyd/client/files.py", line 91, in get_files_in_current_directory
IOError: [Errno 24] Too many open files: './iCloud Drive\xef\xbc\x88\xe5\xbd\x92\xe6\xa1\xa3\xef\xbc\x89 - 1/Sketch/blind_model.png'
adaxi:~ Arduino$ floyd run --mode jupyter --gpu
Error in sys.excepthook:
Traceback (most recent call last):
  File "/Users/Arduino/anaconda2/lib/python2.7/site-packages/raven/base.py", line 274, in handle_exception
  File "/Users/Arduino/anaconda2/lib/python2.7/site-packages/raven/base.py", line 814, in captureException
  File "/Users/Arduino/anaconda2/lib/python2.7/site-packages/raven/base.py", line 634, in capture
  File "/Users/Arduino/anaconda2/lib/python2.7/site-packages/raven/base.py", line 470, in build_msg
  File "/Users/Arduino/anaconda2/lib/python2.7/site-packages/raven/base.py", line 293, in get_processors
  File "/Users/Arduino/anaconda2/lib/python2.7/site-packages/raven/base.py", line 78, in __missing__
ImportError: No module named processors

Original exception was:
Traceback (most recent call last):
  File "/Users/Arduino/anaconda2/bin/floyd", line 11, in <module>
  File "/Users/Arduino/anaconda2/lib/python2.7/site-packages/click/core.py", line 722, in __call__
  File "/Users/Arduino/anaconda2/lib/python2.7/site-packages/click/core.py", line 697, in main
  File "/Users/Arduino/anaconda2/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
  File "/Users/Arduino/anaconda2/lib/python2.7/site-packages/click/core.py", line 895, in invoke
  File "/Users/Arduino/anaconda2/lib/python2.7/site-packages/click/core.py", line 535, in invoke
  File "/Users/Arduino/anaconda2/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
  File "/Users/Arduino/anaconda2/lib/python2.7/site-packages/floyd/cli/run.py", line 221, in run
  File "/Users/Arduino/anaconda2/lib/python2.7/site-packages/floyd/client/module.py", line 37, in create
  File "/Users/Arduino/anaconda2/lib/python2.7/site-packages/floyd/client/files.py", line 91, in get_files_in_current_directory
IOError: [Errno 24] Too many open files: './iCloud Drive\xef\xbc\x88\xe5\xbd\x92\xe6\xa1\xa3\xef\xbc\x89 - 1/Sketch/blind_model.png'

Can you help me to solve it?
Thanks a lot!

**Comment by houqp** [comment]
Hi, the actual error was `Too many open files`. Do you have lots of data files in side the directory where you ran the run command? If so you need to either use .floydignore file to exclude them or upload them separately as a dataset.
