### ISSUE TITLE
Data upload fails

### ISSUE THREAD

**Issue by bartolsthoorn** [floydhub/floyd-cli#17]
Tried it twice, same result.
```
$ floyd data upload
Compressing data ...
Creating data source. Total upload size: 600.5MiB
Uploading compressed data ...
Traceback (most recent call last): 629681357/629681357 - 00:00:00
  File "/home/bart/anaconda3/bin/floyd", line 11, in <module>
    sys.exit(cli())
  File "/home/bart/anaconda3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/bart/anaconda3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/bart/anaconda3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/bart/anaconda3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/bart/anaconda3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/bart/anaconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/bart/anaconda3/lib/python3.6/site-packages/floyd/cli/data.py", line 58, in upload
    data_id = DataClient().create(data)
  File "/home/bart/anaconda3/lib/python3.6/site-packages/floyd/client/data.py", line 69, in create
    timeout=3600)
  File "/home/bart/anaconda3/lib/python3.6/site-packages/floyd/client/base.py", line 57, in request
    self.check_response_status(response)
  File "/home/bart/anaconda3/lib/python3.6/site-packages/floyd/client/base.py", line 81, in check_response_status
    response.raise_for_status()
  File "/home/bart/anaconda3/lib/python3.6/site-packages/requests/models.py", line 909, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: https://www.floydhub.com/api/v1/modules/
```
Looks like it has been broken for a month since this was already mentioned here: [https://forum.floydhub.com/t/getting-connection-issue-when-uploading-the-data/75/5](https://forum.floydhub.com/t/getting-connection-issue-when-uploading-the-data/75/5)

**Comment by mckayward** [comment]
Hey @bartolsthoorn, it's been in the works a while, but the data upload issues (and the ugly stack trace) should be resolved as of cli v0.9.8 :tada:
