### ISSUE TITLE
Jupyter notebook sync fails

### ISSUE THREAD

**Issue by bartolsthoorn** [floydhub/floyd-cli#18]
Trying to start the notebook that also syncs a zip file fails.

I know this zip file should just be uploaded as data instead, but it is probably good to handle this properly with a message like "Max size exceeded" instead of a 500 error.
```
$ floyd run \
  --mode jupyter \
  --env pytorch \
  --gpu
Creating project run. Total upload size: 602.2MiB
Syncing code ...
Traceback (most recent call last): 631501001/631500616 - 00:00:00
  File "/home/bart/anaconda3/bin/floyd", line 11, in <module>
    sys.exit(cli())
  File "/home/bart/anaconda3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/bart/anaconda3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/bart/anaconda3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/bart/anaconda3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/bart/anaconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/bart/anaconda3/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/bart/anaconda3/lib/python3.6/site-packages/floyd/cli/run.py", line 54, in run
    module_id = ModuleClient().create(module)
  File "/home/bart/anaconda3/lib/python3.6/site-packages/floyd/client/module.py", line 54, in create
    timeout=3600)
  File "/home/bart/anaconda3/lib/python3.6/site-packages/floyd/client/base.py", line 57, in request
    self.check_response_status(response)
  File "/home/bart/anaconda3/lib/python3.6/site-packages/floyd/client/base.py", line 81, in check_response_status
    response.raise_for_status()
  File "/home/bart/anaconda3/lib/python3.6/site-packages/requests/models.py", line 909, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: https://www.floydhub.com/api/v1/modules/
```

**Comment by narenst** [comment]
@bartolsthoorn Can you try uploading a smaller code base? Maybe cd into a subdirectory of your project and run floyd run command? I want to see if this is an issue in the server or the CLI.

**Comment by bartolsthoorn** [comment]
When I remove the ~600MiB zip file it works fine, I just think it shouldn't error out like this, that's quite user unfriendly.

Normally I would expect a 500 internal error to be a serious error on the server side that is automatically logged but I'm not sure how the API works.

**Comment by heinze007** [comment]
So do I... I'm afraid Floydhub cannot go further without their improvement in server.

**Comment by oltip** [comment]
I am having problems uploading images in jpg ( only 3) which are in the directory where I cd where I run floyd init. Any suggestion?

**Comment by narenst** [comment]
This issue has been open for a while and refers to different issues. We recently revamped data upload that fixes upload issues. So I'll close this now.

@oltip What is the error you are seeing? Can you share the full error?
