### ISSUE TITLE
Ubuntu installation fails at runtime

### ISSUE THREAD

**Issue by digitalex** [floydhub/floyd-cli#78]
Installed on Ubuntu, using python 2.7.6 under virtualenv. Installation succeeds, but any 'floyd' command fails at runtime;

    floyd --help
	Traceback (most recent call last):
	  File "/usr/local/bin/floyd", line 9, in <module>
	    load_entry_point('floyd-cli==0.10.3', 'console_scripts', 'floyd')()
	  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
	    return get_distribution(dist).load_entry_point(group, name)
	  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2363, in load_entry_point
	    return ep.load()
	  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
	    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
	  File "/usr/local/lib/python2.7/dist-packages/floyd/main.py", line 10, in <module>
	    from floyd.cli.version import upgrade, version
	  File "/usr/local/lib/python2.7/dist-packages/floyd/cli/version.py", line 1, in <module>
	    import pip
	  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 61, in <module>
	    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
	  File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
	    from pip.download import path_to_url
	  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 25, in <module>
	    from requests.compat import IncompleteRead
	ImportError: cannot import name IncompleteRead

**Comment by narenst** [comment]
Is it possible that you have an older version of requests library installed in your global python env? Inside your virtualenv can you try:

`pip install requests -U`

And then installing floyd-cli?

**Comment by digitalex** [comment]
That solved it! Thanks
