### ISSUE TITLE
command line operations on floyd-hub cli giving error 

### ISSUE THREAD

**Issue by shahdivyam** [floydhub/floyd-cli#8]
Traceback (most recent call last):
  File "/usr/local/bin/floyd", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1063, in invoke
    Command.invoke(self, ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/floyd/main.py", line 25, in cli
    check_cli_version()
  File "/usr/local/lib/python2.7/dist-packages/floyd/main.py", line 33, in check_cli_version
    current_version = pkg_resources.require("floyd-cli")[0].version
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 968, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 859, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pathlib2 2.1.0 (/home//.local/lib/python2.7/site-packages), Requirement.parse('pathlib2>=2.2.1'), set(['floyd-cli']))

The error is coming after most recent update to

**Comment by narenst** [comment]
This seems like an issue with conflicting pathlib versions. Are you running this inside a virtualenv?

**Comment by shahdivyam** [comment]
not running in a virtualenv
